# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Enabled by default (v2.6+)
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    
    # Additional recommended linters
    - misspell      # Check for misspelled words
    - unconvert     # Remove unnecessary type conversions
    - dupl          # Check for duplicate code
  
  disable:
    - revive        # Disabled - style suggestions already addressed
    - gocritic      # Disabled - style suggestions (ifElseChain) not needed
    - gocyclo       # Disabled - complexity warnings on pre-existing code
    - unused        # Disabled - test helpers for future BDD scenarios
    - unparam       # Disabled - parameters kept for future use
    - dupl          # Disabled - false positives on BDD test boilerplate

linters-settings:
  gocyclo:
    min-complexity: 20  # Increased from 15 - allow moderately complex functions
  
  dupl:
    threshold: 150  # Tokens threshold for duplicate detection (increased for BDD test boilerplate)
  
  gocritic:
    disabled-checks:
      - ifElseChain  # if-else chains are often more readable than switches
      - exitAfterDefer  # Sometimes intentional (e.g., os.Exit after cleanup)
  
  revive:
    # Disable all revive checks - we've already fixed the important ones
    enable-all-rules: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Exclude unused test helper functions (for future BDD scenarios)
  exclude-rules:
    - path: features/.*_test\.go
      linters:
        - unused
      text: "is unused"
    # Exclude dupl for test files - BDD boilerplate is intentionally similar
    - path: features/
      linters:
        - dupl
    # Exclude unused parameters in runTask - used for future concurrency safety
    - path: main\.go
      linters:
        - unparam
      text: "outputMu is unused"
