# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Enabled by default (v2.6+)
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code
    
    # Additional recommended linters
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - gocritic      # Opinionated Go linter
    - gocyclo       # Check cyclomatic complexity
    - dupl          # Check for duplicate code

linters-settings:
  gocyclo:
    min-complexity: 15  # Warn on functions with complexity > 15
  
  dupl:
    threshold: 100  # Tokens threshold for duplicate detection

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
