version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: devpipe
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: devpipe
    repository:
      owner: drewkhoury
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/drewkhoury/devpipe
    description: Fast, local pipeline runner for development workflows
    license: Apache-2.0
    install: |
      bin.install "devpipe"
    test: |
      system "#{bin}/devpipe", "help"
